/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_probadr98_ndktest_NativeClass.h"
#include<stdio.h>

JNIEXPORT jstring JNICALL Java_com_probadr98_ndktest_NativeClass_getMessageFromJNI
  (JNIEnv *env, jclass obj){

  printf("hello word");
  return env->NewStringUTF("this is from c++");

  }