/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<opencv2/opencv.hpp>
#include<stdio.h>

using namespace cv;
using namespace std;
/* Header for class com_probadr98_ndktest_OpencvNativeClass */

#ifndef _Included_com_probadr98_ndktest_OpencvNativeClass
#define _Included_com_probadr98_ndktest_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_probadr98_ndktest_OpencvNativeClass
 * Method:    ConvertGray
 * Signature: (JJ)I
 */
 int toGray(Mat img,Mat& gray);
JNIEXPORT jint JNICALL Java_com_probadr98_ndktest_OpencvNativeClass_ConvertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
